//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcredetationLevel
    {
        public AcredetationLevel()
        {
            this.ProtocolsRemarks = new HashSet<ProtocolsRemark>();
            this.Tests = new HashSet<Test>();
        }
    
        public System.Guid Id { get; set; }
        public string Level { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProtocolsRemark> ProtocolsRemarks { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
    }
}
