//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionType
    {
        public ActionType()
        {
            this.ActionLogs = new HashSet<ActionLog>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string TypeNameBg { get; set; }
    
        public virtual ICollection<ActionLog> ActionLogs { get; set; }
    }
}
