//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedDiary
    {
        public ArchivedDiary()
        {
            this.ArchivedProtocolResults = new HashSet<ArchivedProtocolResult>();
            this.ArchivedProducts = new HashSet<ArchivedProduct>();
            this.ArchivedProtocolRemarks = new HashSet<ArchivedProtocolRemark>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public System.DateTime AcceptanceDateAndTime { get; set; }
        public string LetterNumber { get; set; }
        public System.DateTime LetterDate { get; set; }
        public string Contractor { get; set; }
        public string Client { get; set; }
        public string Comment { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestAcceptedBy { get; set; }
        public Nullable<int> RequestTestingPeriod { get; set; }
        public System.DateTime ProtocolIssuedDate { get; set; }
        public string ProtocolTester { get; set; }
        public string ProtocolLabLeader { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<ArchivedProtocolResult> ArchivedProtocolResults { get; set; }
        public virtual ICollection<ArchivedProduct> ArchivedProducts { get; set; }
        public virtual ICollection<ArchivedProtocolRemark> ArchivedProtocolRemarks { get; set; }
    }
}
