//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTest
    {
        public ProductTest()
        {
            this.ProtocolResults = new HashSet<ProtocolResult>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid TestId { get; set; }
        public System.Guid TestMethodId { get; set; }
        public string MethodValue { get; set; }
        public string Remark { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TestMethod TestMethod { get; set; }
        public virtual Test Test { get; set; }
        public virtual ICollection<ProtocolResult> ProtocolResults { get; set; }
    }
}
