//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Role
    {
        public Role()
        {
            this.RolesFeatures = new HashSet<RolesFeature>();
            this.Users = new HashSet<User>();
        }

        [Display(Name = "Роля")]
        public System.Guid Id { get; set; }
        [Required(ErrorMessage="Името на ролята е задължително")]
        [Display(Name = "Име")]
        public string DisplayName { get; set; }
    
        public virtual ICollection<RolesFeature> RolesFeatures { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
