//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        [Required(ErrorMessage = "Потребителско име е задължително")]
        [StringLength(100, ErrorMessage = "Потребителското име трябва да бъде поне 5 символа.", MinimumLength = 5)]
        [Display(Name="Потребителско име")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Паролата е задължителна")]
        [StringLength(100, ErrorMessage = "Паролата трябва да бъде поне 6 символа.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Парола")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Името е задължително")]
        [Display(Name = "Име")]
        public string FirstName { get; set; }
        [Display(Name = "Презиме")]
        public string MiddleName { get; set; }
        [Required(ErrorMessage = "Фамилията е задължителна")]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Длъжността е задължителна")]
        [Display(Name = "Длъжност")]
        public string Position { get; set; }
        [Required(ErrorMessage = "Ролята е задължителна")]
        [Display(Name = "Роля")]
        public Nullable<System.Guid> RoleId { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
